name: PHP Static Analysis

on:
  pull_request:

jobs:
  changes:
    name: Detect changes in PHP files
    runs-on: ubuntu-latest

    steps:
      - name: Filter changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            php_files:
              - '*.php'
            phpstan_config:
              - 'phpstan.neon'

  phpstan:
    name: PHPStan
    needs: changes
    if: ${{ needs.changes.outputs.php_files == 'true' || needs.changes.outputs.phpstan_config == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # TODO: Überlegen; als env variable auslagern?
          extensions: dom, curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist

      - name: Run PHPStan
        run: composer analyse
