name: PHP Static Analysis

on:
  pull_request:

jobs:
  detect_changes:
    name: Detect Changes in PHP Files
    runs-on: ubuntu-latest

    outputs:
      php_files_changed: ${{ steps.filter.outputs.php_files }}
      phpstan_config_changed: ${{ steps.filter.outputs.phpstan_config }}

    steps:
      - name: Identify Changed PHP Files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            php_files:
              - added|modified: '*.php'
            phpstan_config:
              - added|modified: 'phpstan.neon'

  run_phpstan:
    name: Run PHPStan Analysis
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.php_files_changed == 'true' || needs.detect_changes.outputs.phpstan_config_changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # TODO: Consider externalizing as an env variable
          extensions: dom, curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPStan
        run: composer analyse
