name: Lint PHP Code Style Issues

on:
  pull_request:

jobs:
  detect_php_changes:
    name: Detect Changes in PHP Files
    runs-on: ubuntu-latest

    outputs:
      php_files_changed: ${{ steps.filter.outputs.php_files }}

    steps:
      - name: Identify Changed PHP Files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            php_files:
              - added|modified: '**/*.php'

  lint_php_code:
    name: Lint PHP Code Styling
    needs: detect_php_changes
    if: ${{ needs.detect_php_changes.outputs.php_files_changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check PHP Code Style
        uses: aglipanci/laravel-pint-action@v2
        with:
          testMode: true
          verboseMode: true
