name: Lint PHP code style issues

on:
  pull_request:

jobs:
  changes:
    name: Detect changes in PHP files
    runs-on: ubuntu-latest

    steps:
      - name: Filter changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            php_files:
              - '*.php'

  lint-php-code-styling:
    name: Lint PHP Code Styling
    needs: changes
    if: ${{ needs.changes.outputs.php_files == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check PHP code style issues
        uses: aglipanci/laravel-pint-action@v2
        with:
          testMode: true
          verboseMode: true
