name: Lint PHP Code Style Issues

on:
  pull_request:

permissions:
  contents: read

jobs:
  detect_php_changes:
    name: Detect Changes in PHP Files
    runs-on: ubuntu-latest

    outputs:
      php_files_changed: ${{ steps.filter.outputs.php_files }}

    steps:
      - name: Identify Changed PHP Files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            php_files:
              - added|modified: '**/*.php'

  lint_php_code:
    name: Lint PHP Code Styling
    needs: detect_php_changes
    if: ${{ needs.detect_php_changes.outputs.php_files_changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Check PHP Code Style
        uses: aglipanci/laravel-pint-action@36de00d5f5a8a4e12d443e01671daa12a18f4c79 # v2.6.0
        with:
          testMode: true
          verboseMode: true
