name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_unit_tests:
    name: Run PHPUnit Tests - php@${{ matrix.setup.php }} - statamic@${{ matrix.setup.statamic }} - laravel@${{ matrix.setup.laravel }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        setup:
          - {
              php: "8.3",
              laravel: "10.*",
              statamic: "4.*",
              testbench: "8.*",
              os: "ubuntu-latest",
            }
          - {
              php: "8.3",
              laravel: "11.*",
              statamic: "5.*",
              testbench: "9.*",
              os: "ubuntu-latest",
            }

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.setup.php }}
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Install Composer Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.setup.laravel }}" "statamic/cms:${{ matrix.setup.statamic }}" "orchestra/testbench:${{ matrix.setup.testbench }}" --no-interaction --no-update
          composer install --no-interaction

      - name: Run PHPUnit Tests
        run: composer test
