name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  workflows:
    uses: 21stdigital/workflows/.github/workflows/validate-pr.yml@main
