---
name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate:
    name: Validate Pull Request Title
    runs-on: [ubuntu-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Conventional Pull Request
        uses: CondeNast/conventional-pull-request-action@v0.2.0
        with:
          commitTitleMatch: "false"
